/*
 * Generated OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ubiquia.test.belief.state.generator.model;


import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.ubiquia.common.model.acl.dto.AbstractAclModel;

/**
 * A base model.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "modelType",
    visible = true)
@JsonSubTypes({
    @JsonSubTypes.Type(value = Animal.class, name = "Animal"),
})

public class BaseModel extends AbstractAclModel {

    @Override
    public String getModelType() {
        return "BaseModel";
    }
}
