/*
 * Generated OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ubiquia.test.belief.state.generator.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ColorType
 */
public enum ColorType {

    BLUE("BLUE"),

    GREEN("GREEN"),

    BROWN("BROWN"),

    BLACK("BLACK"),

    WHITE("WHITE"),

    GRAY("GRAY");

    private String value;

    ColorType(String value) {
        this.value = value;
    }

    @JsonCreator
    public static ColorType fromValue(String value) {
        for (ColorType b : ColorType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}

