{{- if .Values.k8s.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ubiquia.serviceAccountName" . }}
  labels:
    {{- include "ubiquia.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ubiquia.serviceAccountName" . }}
  labels:
    {{- include "ubiquia.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ubiquia.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ubiquia.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
