apiVersion: v1
kind: ConfigMap
metadata:
  name: ubiquia-core-flow-config
data:
  application.yaml: |

    logging:
      level:
        # You haven't seen logs until you've seen this library complain about generating timestamps from JSON schema
        net.jimblackler: OFF
        org.ubiquia: {{ .Values.logging.ubiquia }}

    management:
      endpoint:
        info:
          enabled: true
          java:
            enabled: true
          build:
            enabled: true
          health:
            probes:
              enabled: true
            show-components: always
            show-details: always
          prometheus:
            enabled: true
      endpoints:
        web:
          exposure:
            include: info, prometheus, health
      metrics:
        tags:
          application: ${spring.application.name}

    spring:
      server:
      port: {{ .Values.convenience.variables.spring.port }}

      application:
        name: flow-service
{{ if .Values.ubiquia.agent.database.h2.enabled }}
      datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
        hikari:
          transaction-isolation: {{ .Values.ubiquia.agent.database.transactionIsolation }}
      h2:
        console:
          enabled: true
          path: /h2-console
{{ else if .Values.ubiquia.agent.database.yugabyte.enabled }}
      datasource:
        driverClassName: com.yugabyte.Driver
        url: jdbc:yugabytedb://yb-tservers:5433/yugabyte?autoReconnect=true
        username: yugabyte
        password: yugabyte
        hikari:
          transaction-isolation: {{ .Values.ubiquia.agent.database.transactionIsolation }}
{{ end }}
      jackson:
        date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'"
        deserialization:
          fail-on-unknown-properties: true
      jpa:
        hibernate:
          ddl-auto: {{ .Values.ubiquia.agent.database.ddlAutoSetting }}
        properties:
          hibernate:
            generate_statistics: false
            format_sql: true

    springdoc:
      swagger-ui:
        path: {{ .Values.convenience.variables.spring.swaggerDocs }}
        enabled: true

    ubiquia:
      agent:
        id: {{ .Values.ubiquia.agent.id }}
        flowService:
          bootstrap:
            enabled: {{ .Values.ubiquia.agent.flowService.bootstrap.enabled }}          
            acls:
              enabled: true
              directory: 
                path: /app/etc/acls/
            beliefStates:
              enabled: true
            graphs:
              enabled: true
              directory: 
                path: /app/etc/graphs/
              deployments:
                {{- range $v := .Values.ubiquia.agent.flowService.graph.deployments }}
                - name: {{ $v.name }}
                  version: 
                    major: {{ $v.version.major }}
                    minor: {{ $v.version.minor }}
                    patch: {{ $v.version.patch }}
                  {{- if $v.graphSettings }}
                  graphSettings:
                    flag: {{ $v.graphSettings.flag }}
                  {{- end -}}
                {{- end }}
      kubernetes:
        enabled: true
        namespace: {{ .Release.Namespace }}
      page:
        max-size: 100
