apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubiquia-core-flow-service
  labels:
    {{- include "ubiquia.labels" . | nindent 4 }}
    component: ubiquia-core-flow-service
spec:
  {{- if not .Values.k8s.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "ubiquia.selectorLabels" . | nindent 6 }}
      component: ubiquia-core-flow-service

  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: "{{ .Values.convenience.variables.spring.port }}"

      labels:
        {{- include "ubiquia.selectorLabels" . | nindent 8 }}
        {{- include "ubiquia.podLabels" . | nindent 8 }}
        component: ubiquia-core-flow-service


    spec:
      {{- with .Values.infrastructure.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ubiquia.serviceAccountName" . }}
      volumes:
      - name: ubiquia-flow-bootstrap-acls
        configMap:
          name: ubiquia-flow-bootstrap-acls
      - name: ubiquia-flow-bootstrap-graphs
        configMap:
          name: ubiquia-flow-bootstrap-graphs
      - name: config
        configMap:
          name: ubiquia-core-flow-config
      containers:
      - name: flow-service
        volumeMounts:
        - name: ubiquia-flow-bootstrap-acls
          mountPath: /app/etc/acls
        - name: ubiquia-flow-bootstrap-graphs
          mountPath: /app/etc/graphs
        - name: config
          mountPath: /app/etc
        livenessProbe: 
          httpGet:
            path: /actuator/health
            port: {{ .Values.convenience.variables.spring.port }}
          initialDelaySeconds: 180  
        image: {{ include "ubiquia.core.flowService.image" . }}
        imagePullPolicy: {{ .Values.infrastructure.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.convenience.variables.spring.port }}
            protocol: TCP
