{{ if .Values.k8s.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ubiquia.serviceAccountName" . }}
  labels:
    {{- include "ubiquia.labels" . | nindent 4 }}

---

{{- end }}
