logging:
  ubiquia: INFO

ubiquia:
  cluster:
  agent:
    database: 
      h2:
        enabled: true
      yugabyte:
        enabled: false
    flowService:
      bootstrap:
        enabled: true
        beliefState:
          deployments:
        graph:
          deployments:
            - name: ubiquia-workbench
              version:
                major: 1
                minor: 1
                patch: 0
    storage:  
      minio:
        enabled: false
  components:
    core:
      beliefStateGeneratorService:
        image:
          registry: ubiquia
          repository: core-belief-state-generator-service
          tag: latest
      communicationService:
        image:
          registry: ubiquia
          repository: core-communication-service
          tag: latest
      flowService:
        image:
          registry: ubiquia
          repository: core-flow-service
          tag: latest
    test:
      beliefStateGeneratorService:
        image:
          registry: ubiquia
          repository: test-belief-state-generator-service
          tag: latest
      
infrastructure:
  image:
    pullPolicy: IfNotPresent