logging:
  ubiquia: INFO

ubiquia:
  cluster:
  agent:
    database: 
      h2:
        enabled: true
      yugabyte:
        enabled: false
    flowService:
      bootstrap:
        enabled: true
      graph:
        deployments:
