apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubiquia-core-belief-state-generator-service-belief-state-jars-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ubiquia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: belief-state-storage
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "ubiquia.chart" . }}
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: belief-state-jars-pv
