logging:
  ubiquia: INFO

ubiquia:
  mode: PROD
  cluster:
  agent:
    database:
      type: Postgres
      postgres:
        enabled: true

postgresql:
  auth:
    database: ubiquia
    username: ubiquia
    password: ubiquia
