/*
 * Generated OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ubiquia.test.belief.state.generator.model;


import java.util.ArrayList;
import java.util.List;

/**
 * A model of a person.
 */
public class Person extends BaseModel {
    private ColorType hairColor;
    private Name name;
    private List<Animal> pets = new ArrayList<>();

    public ColorType getHairColor() {
        return hairColor;
    }

    public void setHairColor(ColorType hairColor) {
        this.hairColor = hairColor;
    }

    public Name getName() {
        return name;
    }

    public void setName(Name name) {
        this.name = name;
    }

    public List<Animal> getPets() {
        return pets;
    }

    public void setPets(List<Animal> pets) {
        this.pets = pets;
    }
}
