convenience:
  variables:
    spring:
      port: 8080
      swaggerDocs: /swagger-ui.html
    tls:
      enabled: &tlsEnabled false

ubiquia:
  cluster:
  instance:
    database: 
      ddlAutoSetting: create
      yugabyte:
        enabled: true
      # ANSI Database Level Isolation (https://en.wikipedia.org/wiki/Isolation_(database_systems))
      transactionIsolation: TRANSACTION_READ_COMMITTED # values are: TRANSACTION_READ_UNCOMMITTED (0), TRANSACTION_READ_COMMITTED (1), TRANSACTION_REPEATABLE_READ (2), TRANSACTION_SERIALIZABLE (3)
    flowService:
      bootstrap:
        enabled: true
      graph:
        deployments:
      jvm:
        maxRAMPercentage: 25
  components:
    core:
      commService:
        image:
          registry: *prodRegistry
          repository: amigos
          tag: 0.1.0
      flowService:
        graph:
          image:
            registry: *prodRegistry
            repository: amigos
            tag: 0.1.0

k8s:
  autoscaling:
    enabled: false

infrastructure:
  image:
    pullPolicy: IfNotPresent

# Dependency Overrides
yugabyte:
  enableLoadBalancer: false
  replicas:
    master: 1
    tserver: 1
  storage: 
    ephemeral: true
  istioCompatibility:
    enabled: false