convenience:
  variables:
    spring:
      port: 8080
      swaggerDocs: /swagger-ui/index.html
    tls:
      enabled: &tlsEnabled false

config:
  podLabels: 

ubiquia:
  instance:
    database: 
      ddlAutoSetting: create
      h2:
        enabled: false
      yugabyte:
        enabled: true
      # ANSI Database Level Isolation (https://en.wikipedia.org/wiki/Isolation_(database_systems))
      # values are: TRANSACTION_READ_UNCOMMITTED (0), TRANSACTION_READ_COMMITTED (1), TRANSACTION_REPEATABLE_READ (2), TRANSACTION_SERIALIZABLE (3)
      transactionIsolation: TRANSACTION_READ_COMMITTED 
    flowService:
      bootstrap:
        enabled: true
      graph:
        deployments:
      jvm:
        maxRAMPercentage: 25
  components:
    core:
      communicationService:
        image:
          registry: ubiquia
          repository: core-communication-service
          tag: latest
      flowService:
        image:
          registry: ubiquia
          repository: core-flow-service
          tag: latest

k8s:
  serviceAccount:
    create: true
    name: ubiquia
  autoscaling:
    enabled: false

infrastructure:
  image:
    pullPolicy: IfNotPresent

# Dependency Overrides
yugabyte:
  enableLoadBalancer: false
  replicas:
    master: 1
    tserver: 1
  storage: 
    ephemeral: true
  istioCompatibility:
    enabled: false