apiVersion: v1
kind: ConfigMap
metadata:
  name: ubiquia-core-belief-state-generator-config
data:
  application.yaml: |

    logging:
      level:
        org.ubiquia: {{ .Values.logging.ubiquia }}

    management:
      endpoint:
        info:
          enabled: true
          java:
            enabled: true
          build:
            enabled: true
          health:
            probes:
              enabled: true
            show-components: always
            show-details: always
          prometheus:
            enabled: true
      endpoints:
        web:
          exposure:
            include: info, prometheus, health
      metrics:
        tags:
          application: ${spring.application.name}

    spring:
      server:
      port: {{ .Values.convenience.variables.spring.port }}

      application:
        name: belief-state-generator-service
      jackson:
        date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'"

    springdoc:
      swagger-ui:
        path: {{ .Values.convenience.variables.spring.swaggerDocs }}
        enabled: true

    ubiquia:
      agent:
        id: {{ .Values.ubiquia.agent.id }}
      beliefStateGeneratorService:
        template:
          filepath:
            dto: "/app/etc/resrouces/template/java/dto"
            entity: "/app/etc/resrouces/template/java/entity"
      flow:
        service:
          port: {{ .Values.convenience.variables.spring.port }}
          url: http://ubiquia-core-flow-service