name: Build Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    tags:
      - 'v*'  # Trigger on tag push (e.g., v1.0.0)

env:
  IMAGE_NAME: ubiquia/pet-store-data-transform 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup permissions
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build -x test -x checkstyleMain -x checkstyleTest

  lint:
    runs-on: ubuntu-latest
    needs: build  # Ensure this step runs after the build step
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Setup permissions
        run: chmod +x ./gradlew

      - name: Lint main
        run: ./gradlew checkstyleMain

      - name: Lint test
        run: ./gradlew checkstyleMain

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure this step runs after the build step
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Setup permissions
        run: chmod +x ./gradlew

      - name: Run Tests with Gradle
        run: ./gradlew test
